# Generated by Django 5.2.10 on 2026-02-06 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.CharField(max_length=20)),
                ("class_applied", models.CharField(max_length=10)),
                ("section", models.CharField(blank=True, max_length=5)),
                (
                    "admission_type",
                    models.CharField(
                        choices=[("NEW", "New Admission"), ("TRANSFER", "Transfer")],
                        max_length=10,
                    ),
                ),
                ("admission_date", models.DateField(auto_now_add=True)),
                (
                    "admission_status",
                    models.CharField(
                        choices=[
                            ("ENQUIRY", "Enquiry"),
                            ("APPLIED", "Applied"),
                            ("CONFIRMED", "Confirmed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="ENQUIRY",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "admission_no",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("father_name", models.CharField(max_length=100)),
                ("mother_name", models.CharField(blank=True, max_length=100)),
                ("guardian_name", models.CharField(blank=True, max_length=100)),
                ("primary_mobile", models.CharField(max_length=15, unique=True)),
                ("alternate_mobile", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="AdmissionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=100)),
                (
                    "document_file",
                    models.FileField(blank=True, upload_to="admission/documents/"),
                ),
                ("is_submitted", models.BooleanField(default=False)),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="admission.admission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdmissionFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tuition_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("ONLINE", "Online"),
                            ("CHEQUE", "Cheque"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "admission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="admission.admission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreviousSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(blank=True, max_length=200)),
                ("board", models.CharField(blank=True, max_length=50)),
                ("last_class", models.CharField(blank=True, max_length=20)),
                ("tc_number", models.CharField(blank=True, max_length=50)),
                (
                    "admission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_school",
                        to="admission.admission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("roll_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "student_photo",
                    models.ImageField(blank=True, upload_to="students/photos/"),
                ),
                ("aadhaar_no", models.CharField(blank=True, max_length=12)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="admission.parentprofile",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions",
                        to="schools.school",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="admission",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admission",
                to="admission.studentprofile",
            ),
        ),
    ]
