# Generated by Django 5.2.10 on 2026-02-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="subject",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
