# Generated by Django 5.2.10 on 2026-02-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="class_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="section",
            field=models.CharField(max_length=5),
        ),
    ]
