# Generated by Django 5.2.10 on 2026-02-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_student_class_name_alter_student_section"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
