# Generated by Django 5.2.10 on 2026-02-07 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0002_alter_studentprofile_parent"),
        ("fees", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feepayment",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_payments",
                to="admission.studentprofile",
            ),
        ),
    ]
