# Generated by Django 5.2.10 on 2026-02-11 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0002_alter_studentprofile_parent"),
        ("fees", "0003_alter_feepayment_student"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feepayment",
            options={},
        ),
        migrations.AddField(
            model_name="feepayment",
            name="total_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="feepayment",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="feepayment",
            name="payment_mode",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Online", "Online")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="feepayment",
            name="status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("pending", "Pending")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="feepayment",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_payments",
                to="admission.studentprofile",
            ),
            preserve_default=False,
        ),
    ]
