# Generated by Django 5.2.10 on 2026-02-06 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("ALL", "All Students"),
                            ("TEACHERS", "Teachers Only"),
                            ("CLASS", "Class Wise"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        blank=True,
                        help_text="Required if target is CLASS",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("publish_date", models.DateField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
