# Generated by Django 5.2.10 on 2026-02-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notice",
            name="target",
        ),
        migrations.AddField(
            model_name="notice",
            name="send_to_parents",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notice",
            name="send_to_students",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notice",
            name="send_to_teachers",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notice",
            name="class_name",
            field=models.CharField(
                blank=True,
                help_text="Fill only if class specific",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="publish_date",
            field=models.DateField(),
        ),
    ]
