# Generated by Django 5.2.10 on 2026-02-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0002_remove_notice_target_notice_send_to_parents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="class_name",
            field=models.CharField(
                blank=True,
                help_text="Fill only if class-specific notice for students",
                max_length=10,
                null=True,
            ),
        ),
    ]
