# Generated by Django 5.2.10 on 2026-02-06 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admission", "0001_initial"),
        ("schools", "0001_initial"),
        ("teacher", "0003_teacher_subject_delete_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Present"), ("A", "Absent")], max_length=1
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="admission.studentprofile",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="teacher.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Student Attendance",
                "ordering": ["-date"],
                "unique_together": {("student", "date")},
            },
        ),
    ]
