# Generated by Django 5.2.10 on 2026-02-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date"]},
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="school",
        ),
    ]
