# Generated by Django 5.2.10 on 2026-02-04 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("schools", "0001_initial"),
        ("students", "0001_initial"),
        ("teacher", "0002_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teacher.teacher"
            ),
        ),
        migrations.AddField(
            model_name="attendancesummary",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="schools.school"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="attendancesummary",
            unique_together={("school", "month")},
        ),
    ]
